# JoinCommands by PixelGuy75 Config File;
############################################################################
# {player} = the player that command will be executed towards;
# Command executed when player joins the game;
enablejoin: true
JoinCommand: 
- st {player} §c§lBlackWebPE
# Command executed when player dies;
enabledeath: false
DeathCommand: 
- say {player} OMG
# Command executed when player does /spawn or respawns into the game;
enablespawn: true
RespawnCommand: 
- st §c§lRespawning...
# Command executed when player leaves the game;
enableleave: false
LeaveCommand: 
- say {player} OMG
