# JoinCommand by PixelGuy75 Config File;
############################################################################
# {player} = the player that joins the game;
############################################################################
# Command executed when player joins the game;
JoinCommand: tell {player} You are awesome!
############################################################################
# Command executed when player dies;
DeathCommand: say {player} Died again...
############################################################################
# Command executed when player does /spawn or respawns into the game;
RespawnCommand: tell {player} Welcome to spawn!
############################################################################
# Command executed when player leaves the game;
LeaveCommand: say {player} ragequit from the server!
